pull_request_rules:
  - name: Automatic merge
    conditions:
      - base=master
      - "status-success=ci/circleci: build"
    actions:
      merge:
        strict: true
  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}
