# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  lint:
    working_directory: ~/workspace
    docker:
      - image: node:14.16.1
    steps:
      - checkout
      - restore_cache:
          key: package-lock-json-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Lint
          command: yarn run eslint

workflows:
  Build:
    jobs:
      - lint
