name: Build

on:
  pull_request:
    branches: [ master ]

jobs:
  view_pull_request_author:
    runs-on: ubuntu-latest
    steps:
      - name: View PR author
        run: echo "This PR is opened by ${{ github.event.pull_request.user.login }} ."
